services:
  
  node:
    container_name: node
    image: node:20.11.1-bullseye-slim
    restart: always
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run start"

  nuxt:
    container_name: nuxt
    image: node:20.11.1-bullseye-slim
    working_dir: /usr/src/app
    volumes:
      - ./nuxt:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    tmpfs:
      - /tmp
    command: sh -c "npm install && npm run dev"
    depends_on:
      - node